/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiLearningRouteImport } from './routes/ai-learning'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/_authenticated/parent.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedStudentTestsRouteImport } from './routes/_authenticated/student/tests'
import { Route as AuthenticatedStudentSubjectsRouteImport } from './routes/_authenticated/student/subjects'
import { Route as AuthenticatedStudentStudyPathRouteImport } from './routes/_authenticated/student/study-path'
import { Route as AuthenticatedStudentRetentionRouteImport } from './routes/_authenticated/student/retention'
import { Route as AuthenticatedStudentRecommendationsRouteImport } from './routes/_authenticated/student/recommendations'
import { Route as AuthenticatedStudentQuizzesRouteImport } from './routes/_authenticated/student/quizzes'
import { Route as AuthenticatedStudentProgressRouteImport } from './routes/_authenticated/student/progress'
import { Route as AuthenticatedStudentNotificationsRouteImport } from './routes/_authenticated/student/notifications'
import { Route as AuthenticatedStudentNotesRouteImport } from './routes/_authenticated/student/notes'
import { Route as AuthenticatedStudentMasteryRouteImport } from './routes/_authenticated/student/mastery'
import { Route as AuthenticatedStudentLeaderboardRouteImport } from './routes/_authenticated/student/leaderboard'
import { Route as AuthenticatedStudentCoursesRouteImport } from './routes/_authenticated/student/courses'
import { Route as AuthenticatedStudentAiTutorRouteImport } from './routes/_authenticated/student/ai-tutor'
import { Route as AuthenticatedParentReportsRouteImport } from './routes/_authenticated/parent.reports'
import { Route as AuthenticatedParentAttendanceRouteImport } from './routes/_authenticated/parent.attendance'
import { Route as AuthenticatedParentAnalyticsRouteImport } from './routes/_authenticated/parent.analytics'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedStudentRemediationMicroConceptIdRouteImport } from './routes/_authenticated/student/remediation.$microConceptId'
import { Route as AuthenticatedStudentLearnMicroConceptIdRouteImport } from './routes/_authenticated/student/learn.$microConceptId'
import { Route as AuthenticatedStudentCoursesCourseIdLessonIdRouteImport } from './routes/_authenticated/student/courses.$courseId.$lessonId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLearningRoute = AiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentTestsRoute =
  AuthenticatedStudentTestsRouteImport.update({
    id: '/student/tests',
    path: '/student/tests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSubjectsRoute =
  AuthenticatedStudentSubjectsRouteImport.update({
    id: '/student/subjects',
    path: '/student/subjects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentStudyPathRoute =
  AuthenticatedStudentStudyPathRouteImport.update({
    id: '/student/study-path',
    path: '/student/study-path',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentRetentionRoute =
  AuthenticatedStudentRetentionRouteImport.update({
    id: '/student/retention',
    path: '/student/retention',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentRecommendationsRoute =
  AuthenticatedStudentRecommendationsRouteImport.update({
    id: '/student/recommendations',
    path: '/student/recommendations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentQuizzesRoute =
  AuthenticatedStudentQuizzesRouteImport.update({
    id: '/student/quizzes',
    path: '/student/quizzes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProgressRoute =
  AuthenticatedStudentProgressRouteImport.update({
    id: '/student/progress',
    path: '/student/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentNotificationsRoute =
  AuthenticatedStudentNotificationsRouteImport.update({
    id: '/student/notifications',
    path: '/student/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentNotesRoute =
  AuthenticatedStudentNotesRouteImport.update({
    id: '/student/notes',
    path: '/student/notes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentMasteryRoute =
  AuthenticatedStudentMasteryRouteImport.update({
    id: '/student/mastery',
    path: '/student/mastery',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentLeaderboardRoute =
  AuthenticatedStudentLeaderboardRouteImport.update({
    id: '/student/leaderboard',
    path: '/student/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentCoursesRoute =
  AuthenticatedStudentCoursesRouteImport.update({
    id: '/student/courses',
    path: '/student/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAiTutorRoute =
  AuthenticatedStudentAiTutorRouteImport.update({
    id: '/student/ai-tutor',
    path: '/student/ai-tutor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParentReportsRoute =
  AuthenticatedParentReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentAttendanceRoute =
  AuthenticatedParentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentAnalyticsRoute =
  AuthenticatedParentAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentRemediationMicroConceptIdRoute =
  AuthenticatedStudentRemediationMicroConceptIdRouteImport.update({
    id: '/student/remediation/$microConceptId',
    path: '/student/remediation/$microConceptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentLearnMicroConceptIdRoute =
  AuthenticatedStudentLearnMicroConceptIdRouteImport.update({
    id: '/student/learn/$microConceptId',
    path: '/student/learn/$microConceptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdLessonIdRoute =
  AuthenticatedStudentCoursesCourseIdLessonIdRouteImport.update({
    id: '/$courseId/$lessonId',
    path: '/$courseId/$lessonId',
    getParentRoute: () => AuthenticatedStudentCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-learning': typeof AiLearningRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/demo': typeof DemoRoute
  '/design-system': typeof DesignSystemRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/analytics': typeof AuthenticatedParentAnalyticsRoute
  '/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/parent/reports': typeof AuthenticatedParentReportsRoute
  '/student/ai-tutor': typeof AuthenticatedStudentAiTutorRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/student/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/notes': typeof AuthenticatedStudentNotesRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/quizzes': typeof AuthenticatedStudentQuizzesRoute
  '/student/recommendations': typeof AuthenticatedStudentRecommendationsRoute
  '/student/retention': typeof AuthenticatedStudentRetentionRoute
  '/student/study-path': typeof AuthenticatedStudentStudyPathRoute
  '/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/student/tests': typeof AuthenticatedStudentTestsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/parent/': typeof AuthenticatedParentIndexRoute
  '/student/learn/$microConceptId': typeof AuthenticatedStudentLearnMicroConceptIdRoute
  '/student/remediation/$microConceptId': typeof AuthenticatedStudentRemediationMicroConceptIdRoute
  '/student/courses/$courseId/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-learning': typeof AiLearningRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/demo': typeof DemoRoute
  '/design-system': typeof DesignSystemRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/analytics': typeof AuthenticatedParentAnalyticsRoute
  '/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/parent/reports': typeof AuthenticatedParentReportsRoute
  '/student/ai-tutor': typeof AuthenticatedStudentAiTutorRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/student/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/notes': typeof AuthenticatedStudentNotesRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/quizzes': typeof AuthenticatedStudentQuizzesRoute
  '/student/recommendations': typeof AuthenticatedStudentRecommendationsRoute
  '/student/retention': typeof AuthenticatedStudentRetentionRoute
  '/student/study-path': typeof AuthenticatedStudentStudyPathRoute
  '/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/student/tests': typeof AuthenticatedStudentTestsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/parent': typeof AuthenticatedParentIndexRoute
  '/student/learn/$microConceptId': typeof AuthenticatedStudentLearnMicroConceptIdRoute
  '/student/remediation/$microConceptId': typeof AuthenticatedStudentRemediationMicroConceptIdRoute
  '/student/courses/$courseId/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-learning': typeof AiLearningRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/demo': typeof DemoRoute
  '/design-system': typeof DesignSystemRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/parent/analytics': typeof AuthenticatedParentAnalyticsRoute
  '/_authenticated/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/_authenticated/parent/reports': typeof AuthenticatedParentReportsRoute
  '/_authenticated/student/ai-tutor': typeof AuthenticatedStudentAiTutorRoute
  '/_authenticated/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/_authenticated/student/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/_authenticated/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/_authenticated/student/notes': typeof AuthenticatedStudentNotesRoute
  '/_authenticated/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/_authenticated/student/progress': typeof AuthenticatedStudentProgressRoute
  '/_authenticated/student/quizzes': typeof AuthenticatedStudentQuizzesRoute
  '/_authenticated/student/recommendations': typeof AuthenticatedStudentRecommendationsRoute
  '/_authenticated/student/retention': typeof AuthenticatedStudentRetentionRoute
  '/_authenticated/student/study-path': typeof AuthenticatedStudentStudyPathRoute
  '/_authenticated/student/subjects': typeof AuthenticatedStudentSubjectsRoute
  '/_authenticated/student/tests': typeof AuthenticatedStudentTestsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/parent/': typeof AuthenticatedParentIndexRoute
  '/_authenticated/student/learn/$microConceptId': typeof AuthenticatedStudentLearnMicroConceptIdRoute
  '/_authenticated/student/remediation/$microConceptId': typeof AuthenticatedStudentRemediationMicroConceptIdRoute
  '/_authenticated/student/courses/$courseId/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-learning'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/design-system'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/parent'
    | '/settings'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/parent/analytics'
    | '/parent/attendance'
    | '/parent/reports'
    | '/student/ai-tutor'
    | '/student/courses'
    | '/student/leaderboard'
    | '/student/mastery'
    | '/student/notes'
    | '/student/notifications'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/recommendations'
    | '/student/retention'
    | '/student/study-path'
    | '/student/subjects'
    | '/student/tests'
    | '/admin/'
    | '/parent/'
    | '/student/learn/$microConceptId'
    | '/student/remediation/$microConceptId'
    | '/student/courses/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-learning'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/design-system'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/settings'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/parent/analytics'
    | '/parent/attendance'
    | '/parent/reports'
    | '/student/ai-tutor'
    | '/student/courses'
    | '/student/leaderboard'
    | '/student/mastery'
    | '/student/notes'
    | '/student/notifications'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/recommendations'
    | '/student/retention'
    | '/student/study-path'
    | '/student/subjects'
    | '/student/tests'
    | '/admin'
    | '/parent'
    | '/student/learn/$microConceptId'
    | '/student/remediation/$microConceptId'
    | '/student/courses/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-learning'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/demo'
    | '/design-system'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/schools'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/parent'
    | '/_authenticated/settings'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/users'
    | '/_authenticated/parent/analytics'
    | '/_authenticated/parent/attendance'
    | '/_authenticated/parent/reports'
    | '/_authenticated/student/ai-tutor'
    | '/_authenticated/student/courses'
    | '/_authenticated/student/leaderboard'
    | '/_authenticated/student/mastery'
    | '/_authenticated/student/notes'
    | '/_authenticated/student/notifications'
    | '/_authenticated/student/progress'
    | '/_authenticated/student/quizzes'
    | '/_authenticated/student/recommendations'
    | '/_authenticated/student/retention'
    | '/_authenticated/student/study-path'
    | '/_authenticated/student/subjects'
    | '/_authenticated/student/tests'
    | '/_authenticated/admin/'
    | '/_authenticated/parent/'
    | '/_authenticated/student/learn/$microConceptId'
    | '/_authenticated/student/remediation/$microConceptId'
    | '/_authenticated/student/courses/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiLearningRoute: typeof AiLearningRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DemoRoute: typeof DemoRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-learning': {
      id: '/ai-learning'
      path: '/ai-learning'
      fullPath: '/ai-learning'
      preLoaderRoute: typeof AiLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/': {
      id: '/_authenticated/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/tests': {
      id: '/_authenticated/student/tests'
      path: '/student/tests'
      fullPath: '/student/tests'
      preLoaderRoute: typeof AuthenticatedStudentTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/subjects': {
      id: '/_authenticated/student/subjects'
      path: '/student/subjects'
      fullPath: '/student/subjects'
      preLoaderRoute: typeof AuthenticatedStudentSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/study-path': {
      id: '/_authenticated/student/study-path'
      path: '/student/study-path'
      fullPath: '/student/study-path'
      preLoaderRoute: typeof AuthenticatedStudentStudyPathRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/retention': {
      id: '/_authenticated/student/retention'
      path: '/student/retention'
      fullPath: '/student/retention'
      preLoaderRoute: typeof AuthenticatedStudentRetentionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/recommendations': {
      id: '/_authenticated/student/recommendations'
      path: '/student/recommendations'
      fullPath: '/student/recommendations'
      preLoaderRoute: typeof AuthenticatedStudentRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/quizzes': {
      id: '/_authenticated/student/quizzes'
      path: '/student/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof AuthenticatedStudentQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/progress': {
      id: '/_authenticated/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof AuthenticatedStudentProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/notifications': {
      id: '/_authenticated/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AuthenticatedStudentNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/notes': {
      id: '/_authenticated/student/notes'
      path: '/student/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof AuthenticatedStudentNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/mastery': {
      id: '/_authenticated/student/mastery'
      path: '/student/mastery'
      fullPath: '/student/mastery'
      preLoaderRoute: typeof AuthenticatedStudentMasteryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/leaderboard': {
      id: '/_authenticated/student/leaderboard'
      path: '/student/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof AuthenticatedStudentLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/courses': {
      id: '/_authenticated/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AuthenticatedStudentCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/ai-tutor': {
      id: '/_authenticated/student/ai-tutor'
      path: '/student/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof AuthenticatedStudentAiTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent/reports': {
      id: '/_authenticated/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof AuthenticatedParentReportsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/attendance': {
      id: '/_authenticated/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof AuthenticatedParentAttendanceRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/analytics': {
      id: '/_authenticated/parent/analytics'
      path: '/analytics'
      fullPath: '/parent/analytics'
      preLoaderRoute: typeof AuthenticatedParentAnalyticsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/remediation/$microConceptId': {
      id: '/_authenticated/student/remediation/$microConceptId'
      path: '/student/remediation/$microConceptId'
      fullPath: '/student/remediation/$microConceptId'
      preLoaderRoute: typeof AuthenticatedStudentRemediationMicroConceptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/learn/$microConceptId': {
      id: '/_authenticated/student/learn/$microConceptId'
      path: '/student/learn/$microConceptId'
      fullPath: '/student/learn/$microConceptId'
      preLoaderRoute: typeof AuthenticatedStudentLearnMicroConceptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/courses/$courseId/$lessonId': {
      id: '/_authenticated/student/courses/$courseId/$lessonId'
      path: '/$courseId/$lessonId'
      fullPath: '/student/courses/$courseId/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentAnalyticsRoute: typeof AuthenticatedParentAnalyticsRoute
  AuthenticatedParentAttendanceRoute: typeof AuthenticatedParentAttendanceRoute
  AuthenticatedParentReportsRoute: typeof AuthenticatedParentReportsRoute
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentAnalyticsRoute: AuthenticatedParentAnalyticsRoute,
  AuthenticatedParentAttendanceRoute: AuthenticatedParentAttendanceRoute,
  AuthenticatedParentReportsRoute: AuthenticatedParentReportsRoute,
  AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedStudentCoursesRouteChildren {
  AuthenticatedStudentCoursesCourseIdLessonIdRoute: typeof AuthenticatedStudentCoursesCourseIdLessonIdRoute
}

const AuthenticatedStudentCoursesRouteChildren: AuthenticatedStudentCoursesRouteChildren =
  {
    AuthenticatedStudentCoursesCourseIdLessonIdRoute:
      AuthenticatedStudentCoursesCourseIdLessonIdRoute,
  }

const AuthenticatedStudentCoursesRouteWithChildren =
  AuthenticatedStudentCoursesRoute._addFileChildren(
    AuthenticatedStudentCoursesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentAiTutorRoute: typeof AuthenticatedStudentAiTutorRoute
  AuthenticatedStudentCoursesRoute: typeof AuthenticatedStudentCoursesRouteWithChildren
  AuthenticatedStudentLeaderboardRoute: typeof AuthenticatedStudentLeaderboardRoute
  AuthenticatedStudentMasteryRoute: typeof AuthenticatedStudentMasteryRoute
  AuthenticatedStudentNotesRoute: typeof AuthenticatedStudentNotesRoute
  AuthenticatedStudentNotificationsRoute: typeof AuthenticatedStudentNotificationsRoute
  AuthenticatedStudentProgressRoute: typeof AuthenticatedStudentProgressRoute
  AuthenticatedStudentQuizzesRoute: typeof AuthenticatedStudentQuizzesRoute
  AuthenticatedStudentRecommendationsRoute: typeof AuthenticatedStudentRecommendationsRoute
  AuthenticatedStudentRetentionRoute: typeof AuthenticatedStudentRetentionRoute
  AuthenticatedStudentStudyPathRoute: typeof AuthenticatedStudentStudyPathRoute
  AuthenticatedStudentSubjectsRoute: typeof AuthenticatedStudentSubjectsRoute
  AuthenticatedStudentTestsRoute: typeof AuthenticatedStudentTestsRoute
  AuthenticatedStudentLearnMicroConceptIdRoute: typeof AuthenticatedStudentLearnMicroConceptIdRoute
  AuthenticatedStudentRemediationMicroConceptIdRoute: typeof AuthenticatedStudentRemediationMicroConceptIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentAiTutorRoute: AuthenticatedStudentAiTutorRoute,
  AuthenticatedStudentCoursesRoute:
    AuthenticatedStudentCoursesRouteWithChildren,
  AuthenticatedStudentLeaderboardRoute: AuthenticatedStudentLeaderboardRoute,
  AuthenticatedStudentMasteryRoute: AuthenticatedStudentMasteryRoute,
  AuthenticatedStudentNotesRoute: AuthenticatedStudentNotesRoute,
  AuthenticatedStudentNotificationsRoute:
    AuthenticatedStudentNotificationsRoute,
  AuthenticatedStudentProgressRoute: AuthenticatedStudentProgressRoute,
  AuthenticatedStudentQuizzesRoute: AuthenticatedStudentQuizzesRoute,
  AuthenticatedStudentRecommendationsRoute:
    AuthenticatedStudentRecommendationsRoute,
  AuthenticatedStudentRetentionRoute: AuthenticatedStudentRetentionRoute,
  AuthenticatedStudentStudyPathRoute: AuthenticatedStudentStudyPathRoute,
  AuthenticatedStudentSubjectsRoute: AuthenticatedStudentSubjectsRoute,
  AuthenticatedStudentTestsRoute: AuthenticatedStudentTestsRoute,
  AuthenticatedStudentLearnMicroConceptIdRoute:
    AuthenticatedStudentLearnMicroConceptIdRoute,
  AuthenticatedStudentRemediationMicroConceptIdRoute:
    AuthenticatedStudentRemediationMicroConceptIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AiLearningRoute: AiLearningRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DemoRoute: DemoRoute,
  DesignSystemRoute: DesignSystemRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
